### ISSUE TITLE
Reintroduce Dependabot for just GitHub Actions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/robotoff#1104]
Reintroduce Dependabot for just GitHub Actions

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 30
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 30
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 30

```
